import {
  Baby,
  Bike,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  Car,
  Church,
  Clapperboard,
  Code2,
  Cpu,
  Dices,
  Film,
  FlaskConical,
  Gamepad2,
  Gem,
  Globe,
  Goal,
  GraduationCap,
  Hammer,
  HandHeart,
  Hash,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laugh,
  LineChart,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Monitor,
  Moon,
  MoreHorizontal,
  Music2,
  Newspaper,
  Palette,
  PartyPopper,
  PawPrint,
  Plane,
  Puzzle,
  Rocket,
  ScrollText,
  Shirt,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Swords,
  Trees,
  Trophy,
  Tv,
  Users,
  UsersRound,
  UtensilsCrossed,
  Video,
  Vote,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export type CommunityCategory = { slug: string; label: string; icon: LucideIcon };

/**
 * Categoria = área geral da comunidade (o seletor de criar/editar mostra todas).
 * "Sem categoria" é a opção vazia do seletor (salva como nulo), por isso não entra aqui.
 * Os códigos já usados no banco (tecnologia, games, musica, arte-design, fotografia, esportes,
 * viagens, anime, cultura, outros) foram mantidos para as comunidades existentes continuarem certas.
 */
export const COMMUNITY_CATEGORIES: CommunityCategory[] = [
  { slug: "tecnologia", label: "Tecnologia", icon: Cpu },
  { slug: "computadores", label: "Computadores", icon: Monitor },
  { slug: "programacao", label: "Programação e Desenvolvimento", icon: Code2 },
  { slug: "inteligencia-artificial", label: "Inteligência Artificial", icon: Bot },
  { slug: "internet-redes-sociais", label: "Internet e Redes Sociais", icon: Globe },
  { slug: "games", label: "Games", icon: Gamepad2 },
  { slug: "e-sports", label: "E-sports", icon: Trophy },
  { slug: "musica", label: "Música", icon: Music2 },
  { slug: "cinema", label: "Cinema", icon: Film },
  { slug: "series-tv", label: "Séries e TV", icon: Tv },
  { slug: "anime", label: "Animes e Mangás", icon: Sparkles },
  { slug: "livros-literatura", label: "Livros e Literatura", icon: BookOpen },
  { slug: "arte-design", label: "Arte e Design", icon: Palette },
  { slug: "fotografia", label: "Fotografia", icon: Camera },
  { slug: "videos-conteudo", label: "Vídeos e Criação de Conteúdo", icon: Video },
  { slug: "entretenimento", label: "Entretenimento", icon: PartyPopper },
  { slug: "cultura", label: "Cultura", icon: Landmark },
  { slug: "cultura-pop", label: "Cultura Pop", icon: Star },
  { slug: "fandoms", label: "Fandoms", icon: Heart },
  { slug: "humor-memes", label: "Humor e Memes", icon: Laugh },
  { slug: "noticias", label: "Notícias e Atualidades", icon: Newspaper },
  { slug: "ciencia", label: "Ciência", icon: FlaskConical },
  { slug: "educacao", label: "Educação", icon: GraduationCap },
  { slug: "historia", label: "História", icon: ScrollText },
  { slug: "filosofia", label: "Filosofia", icon: Brain },
  { slug: "sociedade", label: "Sociedade", icon: UsersRound },
  { slug: "comunidade", label: "Comunidade", icon: Users },
  { slug: "politica", label: "Política", icon: Vote },
  { slug: "economia-financas", label: "Economia e Finanças", icon: LineChart },
  { slug: "negocios", label: "Negócios", icon: Briefcase },
  { slug: "empreendedorismo", label: "Empreendedorismo", icon: Rocket },
  { slug: "marketing-publicidade", label: "Marketing e Publicidade", icon: Megaphone },
  { slug: "profissoes-carreira", label: "Profissões e Carreira", icon: Briefcase },
  { slug: "saude-bem-estar", label: "Saúde e Bem-estar", icon: HeartPulse },
  { slug: "beleza", label: "Beleza", icon: Gem },
  { slug: "moda", label: "Moda", icon: Shirt },
  { slug: "esportes", label: "Esportes", icon: Medal },
  { slug: "futebol", label: "Futebol", icon: Goal },
  { slug: "automobilismo", label: "Automobilismo", icon: Car },
  { slug: "motociclismo", label: "Motociclismo", icon: Bike },
  { slug: "viagens", label: "Viagens", icon: Plane },
  { slug: "turismo", label: "Turismo", icon: Map },
  { slug: "natureza", label: "Natureza", icon: Trees },
  { slug: "animais-pets", label: "Animais e Pets", icon: PawPrint },
  { slug: "culinaria-gastronomia", label: "Culinária e Gastronomia", icon: UtensilsCrossed },
  { slug: "casa-jardim", label: "Casa e Jardim", icon: Home },
  { slug: "faca-voce-mesmo", label: "Faça Você Mesmo", icon: Hammer },
  { slug: "relacionamentos", label: "Relacionamentos", icon: HandHeart },
  { slug: "familia", label: "Família", icon: Users },
  { slug: "maternidade-paternidade", label: "Maternidade e Paternidade", icon: Baby },
  { slug: "hobbies-colecionismo", label: "Hobbies e Colecionismo", icon: Puzzle },
  { slug: "religiao-espiritualidade", label: "Religião e Espiritualidade", icon: Church },
  { slug: "astrologia-esoterismo", label: "Astrologia e Esoterismo", icon: Moon },
  { slug: "rpg-roleplay", label: "RPG e Roleplay", icon: Dices },
  { slug: "comunidades-fas", label: "Comunidades de Fãs", icon: Swords },
  { slug: "clubes-organizacoes", label: "Clubes e Organizações", icon: Building2 },
  { slug: "eventos", label: "Eventos", icon: CalendarDays },
  { slug: "compras-produtos", label: "Compras e Produtos", icon: ShoppingBag },
  { slug: "servicos", label: "Serviços", icon: Wrench },
  { slug: "mercado-classificados", label: "Mercado e Classificados", icon: Store },
  { slug: "comunidades-locais", label: "Comunidades Locais", icon: MapPin },
  { slug: "outros", label: "Outros", icon: MoreHorizontal },
];

/** Código antigo que não é mais oferecido, só para exibir certo se aparecer no banco. */
const LEGACY_LABELS: Record<string, string> = { "cinema-series": "Cinema e Séries" };

/**
 * Os mesmos 11 atalhos de categoria que as telas de Explorar e Comunidades já mostravam
 * (a grade continua do mesmo tamanho; a lista completa fica no seletor de criar/editar).
 */
const featured = (slug: string, label: string, icon?: LucideIcon): CommunityCategory => {
  const c = COMMUNITY_CATEGORIES.find((x) => x.slug === slug);
  return { slug, label, icon: icon ?? c?.icon ?? Hash };
};
export const FEATURED_CATEGORIES: CommunityCategory[] = [
  featured("tecnologia", "Tecnologia"),
  featured("games", "Games"),
  featured("musica", "Música"),
  featured("cinema", "Cinema", Clapperboard),
  featured("arte-design", "Arte e Design"),
  featured("fotografia", "Fotografia"),
  featured("esportes", "Esportes", Trophy),
  featured("viagens", "Viagens"),
  featured("anime", "Anime"),
  featured("cultura", "Cultura", BookOpen),
  featured("outros", "Mais"),
];

export function categoryLabel(slug: string | null) {
  return COMMUNITY_CATEGORIES.find((c) => c.slug === slug)?.label ?? (slug ? LEGACY_LABELS[slug] : undefined) ?? slug ?? null;
}
