-- Pacotes animados Órbita X (astronauta, lobo e alienígenas), gerados a partir das cartelas enviadas.
-- Arquivos em public/stickers/<pack>/<slug>.webp (animado, 256 px) e <slug>-s.webp (prévia).
with src(id, name, descr, cats, cat, ord, slugs, labels) as (values
('astronauta-x','Astronauta X','O astronauta do Órbita X, agora animado: olá, café, sextou e tudo do dia a dia.',array['espaco','orbita-x','cumprimentos'],'espaco',200,array['ola','to-aqui','coracao','ai-sim','bom-dia','cafe-primeiro','boa-noite','oie','tranquilo','musica-e-vida','bora-trabalhar','sextou','te-amo','amizade','serio','que-isso','bora-comer','pizza','que-lindo','chorei','kkkkk','que-fofo','boa-ideia','top','calma','descanso','to-online','voltei','valeu','por-favor','com-certeza','parabens','aff','oi','humanos-tambem-sao-incriveis','modo-foco','meu-mundo'],array['Olá!','Tô aqui!','Coração','Ai sim!','Bom dia!','Café primeiro!','Boa noite!','Oie?','Tranquilo!','Música é vida!','Bora trabalhar?','Sextou!','Te amo!','Amizade!','Sério?','Que isso?!','Bora comer?','Pizza!','Que lindo!','Chorei!','Kkkkk!','Que fofo!','Boa ideia!','Top!','Calma...','Descanso...','Tô online!','Voltei!','Valeu!','Por favor!','Com certeza!','Parabéns!','Aff...','Oi?','Humanos também são incríveis','Modo foco!','Meu mundo!']),
('space-wolf','Space Wolf','O lobo mais estiloso da galáxia, animado pra cada conversa.',array['animais','fofo','cumprimentos'],'animais',201,array['ola','to-aqui','coracao','ai-sim','bom-dia','cafe-primeiro','boa-noite','bora','musica-e-terapia','bora-trabalhar','sextou','te-amo','amizade','partiu','serio','que-isso','chorei','kkkkk','aff','humm','tranquilo','valeu','bora-comer','pizza','que-lindo','to-com-saudade','to-online','descanso','bora-jogar','top','parabens','presente-pra-voce','uau','oi','nao','sim','relax','meu-mundo'],array['Olá!','Tô aqui!','Coração','Ai sim!','Bom dia!','Café primeiro!','Boa noite!','Bora!','Música é terapia!','Bora trabalhar?','Sextou!','Te amo!','Amizade!','Partiu?','Sério?','Que isso?!','Chorei!','Kkkkk','Aff...','Humm...','Tranquilo!','Valeu!','Bora comer?','Pizza!','Que lindo!','Tô com saudade...','Tô online!','Descanso...','Bora jogar?','Top!','Parabéns!','Presente pra você!','Uau!','Oi?','Não!','Sim!','Relax...','Meu mundo!']),
('alien-x','Alienígenas · Órbita X','Os ETs do Órbita X animados: oi, sumido(a), online, offline e muito mais.',array['espaco','engracados','cumprimentos'],'espaco',202,array['ola','tudo-bem','to-aqui','ai-sim','bom-dia','boa-tarde','boa-noite','bora','partiu','voltei','valeu','obrigado','de-nada','te-amo','to-com-saudade','voce-e-incrivel','musica-e-terapia','bora-trabalhar','foco','descanso','cafe-primeiro','bora-comer','hummm','pizza','hoje-nao','to-cansado','preciso-de-cafe','modo-serio','tranquilo','suave','que-fofo','que-isso','haha','chorei','kkkk','ohhh','mds','serio','entendi','boa-ideia','concordo','discordo','calma','respira','paciencia','to-de-boa','ta-certo','fechado','top','ate-mais','oi','sumido-a','cade-voce','online','offline','gg','game-over','bora-jogar','navegando'],array['Olá!','Tudo bem?','Tô aqui!','Ai sim!','Bom dia!','Boa tarde!','Boa noite!','Bora?','Partiu!','Voltei!','Valeu!','Obrigado!','De nada!','Te amo!','Tô com saudade...','Você é incrível!','Música é terapia!','Bora trabalhar?','Foco!','Descanso...','Café primeiro!','Bora comer?','Hummm...','Pizza?','Hoje não!','Tô cansado...','Preciso de café...','Modo sério','Tranquilo!','Suave!','Que fofo!','Que isso?!','Haha!','Chorei!','Kkkk','Ohhh!','Mds!','Sério?!','Entendi!','Boa ideia!','Concordo!','Discordo!','Calma!','Respira...','Paciência...','Tô de boa!','Tá certo!','Fechado!','Top!','Até mais!','Oi?','Sumido(a)!','Cadê você?','Online','Offline','GG!','Game over!','Bora jogar?','Navegando...']),
('alien-x-vibes','Alienígenas · Vibes','Mais ETs animados com as melhores vibes: zen, férias, filminho e cia.',array['espaco','fofo','frases'],'espaco',203,array['ola','e-ai','coracao','tamo-junto','bora','show','cafe','boa-noite','bora-trabalhar','sextou','fofo','musica-e-vida','bora-jogar','filminho','te-amo','que-lindo','que-isso','kkkkk','ai-meu-deus','aff','to-de-boa','zen','pizza','amizade','to-online','oi','humm','de-nada','partiu','gratidao','boa-ideia','planejando','humanos-tambem-sao-incriveis','respeito','modo-noturno','pra-voce','saudade','meu-mundo','hehe','foco','relax'],array['Olá!','E aí?','Coração','Tamo junto!','Bora!','Show!','Café?','Boa noite!','Bora trabalhar?','Sextou!','Fofo!','Música é vida!','Bora jogar?','Filminho?','Te amo!','Que lindo!','Que isso?','Kkkkk','Ai meu Deus!','Aff...','Tô de boa!','Zen...','Pizza!','Amizade!','Tô online!','Oi?','Humm...','De nada!','Partiu!','Gratidão!','Boa ideia!','Planejando...','Humanos também são incríveis','Respeito!','Modo noturno','Pra você!','Saudade...','Meu mundo!','hehe','Foco!','Relax...'])
), packs as (
  insert into public."StickerPack" (id, name, tier, "priceCoins", "isAdult", "sortOrder", cover, stickers, labels, active, section, category, animated, creator, description, categories, rating, published, featured, "isDefault", exclusive)
  select id, name, 'free', null, false, ord, slugs[1], slugs, labels, true, 'adesivos', cat, true, 'Órbita X', descr, cats, 'livre', true, true, true, false from src
  on conflict (id) do update set name = excluded.name, cover = excluded.cover, stickers = excluded.stickers, labels = excluded.labels, animated = true,
    description = excluded.description, categories = excluded.categories, featured = true, "isDefault" = true, active = true, published = true, "updatedAt" = now()
  returning id
), prod as (
  insert into public."StoreProduct" (id, kind, "refId", name, description, image, "priceCoins", tier, "isAdult", badge, "sortOrder", active, meta)
  select 'pack-' || id, 'sticker_pack', id, name, cardinality(slugs) || ' adesivos animados', '/stickers/' || id || '/' || slugs[1] || '-s.webp', 0, 'free', false, 'Novo', ord, true,
    jsonb_build_object('about', descr, 'count', cardinality(slugs), 'rating', 'livre', 'creator', 'Órbita X', 'section', 'adesivos', 'animated', true, 'category', cat, 'categories', to_jsonb(cats))
  from src
  on conflict (id) do update set name = excluded.name, description = excluded.description, image = excluded.image, meta = excluded.meta, active = true
  returning id
)
insert into public."Sticker" (id, "packId", slug, label, keywords, storage, file, preview, format, mime, width, height, bytes, size, "hasText", rating, "sortOrder", active)
select s.id || '/' || u.slug, s.id, u.slug, u.label,
  array(select w from regexp_split_to_table(lower(regexp_replace(u.label, '[!?.()]', '', 'g')), ' +') w where char_length(w) > 1),
  'app', s.id || '/' || u.slug || '.webp', s.id || '/' || u.slug || '-s.webp', 'animated', 'image/webp', 256, 256, 110000, 'normal', u.label <> 'Coração', 'livre', u.n, true
from src s cross join lateral unnest(s.slugs, s.labels) with ordinality as u(slug, label, n)
on conflict (id) do update set label = excluded.label, keywords = excluded.keywords, file = excluded.file, preview = excluded.preview, format = 'animated',
  width = 256, height = 256, "sortOrder" = excluded."sortOrder", active = true;
